language: python
python:
  - 2.7
  - pypy2.7-5.8.0
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy3.5-5.8.0

os:
  - linux

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 2*  ]]; then pip install --allow-all-external mock; fi

script:
- python -m pytest --cov=pytest_watch pytest_watch
